/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'kontiki' at '11/8/15 11:35 AM' with Gradle 2.1
 *
 * @author kontiki, @date 11/8/15 11:35 AM
 */

import org.junit.runner.RunWith
import org.scalatest.FunSuite
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {

//    val content =  scala.io.Source.fromInputStream( getClass.getResourceAsStream("page_1.wiki")).mkString
//    val extractor = new Extractor
//    extractor.load(content)
//    extractor.getInternalLinks.foreach(println)
//
//    assert(library.someLibraryMethod)
  }
}
